apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
    # - image: lucasmsa/tickety-auth
    - image: us.gcr.io/tickety-dev-383517/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  googleCloudBuild:
    projectId: tickety-dev-383517
manifests:
  rawYaml:
    - ./infra/k8s/*
